using GraphQL.Types;
using GraphQLMicroservice.Entities;

namespace GraphQLMicroservice.Queries.Types
{
    public class MaterialType : ObjectGraphType<Material>
    {
        public MaterialType()
        {
            Field(x => x.Id);
            Field(x => x.CreatedOn);
            Field(x => x.CreatedBy);
            Field(x => x.UpdatedOn);
            Field(x => x.UpdatedBy);
            Field<OwnerType>("owner");
            Field(x => x.Name);
            Field(x => x.AlternativeNames);
            Field(x => x.Description);
            Field(x => x.DatasheetLink);
            Field(x => x.Gwp);
            Field(x => x.GwpPerCategoryDeclaredUnit);
            Field(x => x.GwpPerKg);
            Field(x => x.GwpZ);
            Field(x => x.Pct80GwpPerCategoryDeclaredUnit);
            Field(x => x.ConservativeEstimate);
            Field(x => x.BestPractice);
            Field(x => x.ConcreteCompressiveStrength28D);
            Field(x => x.ConcreteCompressiveStrengthOther);
            Field(x => x.ConcreteCompressiveStrengthOtherD, nullable: true);
            Field(x => x.ConcreteFlexionStrength);
            Field(x => x.ConcreteSlump);
            Field(x => x.ConcreteMinSlump);
            Field(x => x.ConcreteMaxSlump);
            Field(x => x.ConcreteAggregateSizeMax);
            Field(x => x.ConcreteMinPipelineSize);
            Field(x => x.ConcreteWCRatio);
            Field(x => x.ConcreteScmMin);
            Field(x => x.ConcreteScmMax);
            Field<ConcreteScmDetailsType>("scnmdetails");
            Field(x => x.ConcreteAirEntrain);
            Field(x => x.ConcreteCo2Entrain);
            Field(x => x.WhiteCement);
            Field(x => x.LightWeight);
            Field(x => x.Density);
            Field(x => x.SteelUltimTensileStrMin);
            Field(x => x.SteelYieldTensileStrMin);
            Field(x => x.SteelBarElongationMin);
            Field(x => x.SteelRecycledContent);
            Field(x => x.SteelPostConsumerRecycledContent);
            Field(x => x.SteelAstmMarking);
            Field(x => x.SteelEuroMarking);
            Field(x => x.SteelRebarDiameterMin);
            Field(x => x.SteelRebarBendingPinMax);
            Field(x => x.SteelRebarTsYsRatioMax);
            Field(x => x.SteelModulusOfElasticity);
            Field(x => x.SteelThermalExpansion);
            Field(x => x.SteelThermalConductivity);
            Field(x => x.ColdFinished);
            Field(x => x.Galvanized);
            Field(x => x.GypsumFireRating);
            Field(x => x.GypsumThickness);
            Field(x => x.GypsumSpecificDensity);
            Field(x => x.GypsumRFactor);
            Field(x => x.GypsumFlameSpreadAstmE84);
            Field(x => x.GypsumSmokeProductionAstmE84);
            Field(x => x.GypsumSurfaceAbrasionD4977);
            Field(x => x.GypsumIndentationD5420);
            Field(x => x.GypsumSoftBodyImpactE695);
            Field(x => x.GypsumHardBodyImpactC1929);
            Field(x => x.BiogenicEmbodiedCarbon);
            Field(x => x.BiogenicEmbodiedCarbonZ);
            Field(x => x.TimberStoredCarbon);
            Field(x => x.TimberStoredCarbonZ);
            Field(x => x.MaxSize);
            Field(x => x.SpecificGravity);
            Field(x => x.RecommendedApplication);
            Field(x => x.ImageLink);
            Field(x => x.ReferenceServiceLife);
            Field(x => x.IntendedApplication);
            Field(x => x.InsulationIntendedApplication);
            Field(x => x.ManufacturerType);
            Field(x => x.FormFactor);
            Field(x => x.YarnWeight);
            Field(x => x.YarnType);
            Field(x => x.Cushioned);
            Field(x => x.Bleachable);
            Field(x => x.FireRadiantPanelRatingAstme648);
            Field(x => x.FireSmokeDensityRatingAstme648);
            Field(x => x.VocEmissions);
            Field(x => x.Thickness);
            Field(x => x.SurfaceArea);
            Field(x => x.StaticLoad);
            Field(x => x.AcousticsNrc);
            Field(x => x.RecycledContent);
            Field(x => x.InsulatingMaterial);
            Field(x => x.FoamType);
            Field(x => x.ThicknessPerDeclaredUnit);
            Field(x => x.CeilingPanelCoreMaterial);
            Field(x => x.CeilingPanelNrc);
            Field(x => x.CeilingPanelCac);
            Field(x => x.Features);
            Field(x => x.WeatherExposed);
            Field(x => x.Fabrication);
            Field(x => x.TimberSpecies);
            Field<ManufacturerType>("manufacturer");
            Field<PlantType>("plant");
            Field(x => x.EpdId);
        }
    }
}
